"""Create metrics and alerts tables

Revision ID: 88789e7a81c0
Revises: 
Create Date: 2026-08-16 14:24:19.162419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88789e7a81c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('contributing_features', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_datapoints',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_datapoints_service_name'), 'metric_datapoints', ['service_name'], unique=False)
    op.create_index(op.f('ix_metric_datapoints_timestamp'), 'metric_datapoints', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_datapoints_timestamp'), table_name='metric_datapoints')
    op.drop_index(op.f('ix_metric_datapoints_service_name'), table_name='metric_datapoints')
    op.drop_table('metric_datapoints')
    op.drop_table('alerts')
    # ### end Alembic commands ###
