"""add metric aggregations table

Revision ID: 9695e773ac65
Revises: 88789e7a81c0
Create Date: 2026-08-17 13:24:06.470450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9695e773ac65'
down_revision: Union[str, None] = '88789e7a81c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_aggregations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_size', sa.String(length=20), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('avg_value', sa.Float(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_aggregations_service_name'), 'metric_aggregations', ['service_name'], unique=False)
    op.create_index(op.f('ix_metric_aggregations_window_start'), 'metric_aggregations', ['window_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_aggregations_window_start'), table_name='metric_aggregations')
    op.drop_index(op.f('ix_metric_aggregations_service_name'), table_name='metric_aggregations')
    op.drop_table('metric_aggregations')
    # ### end Alembic commands ###
